# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='id',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='object_id',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
